Llama-Index Nodes, Utilities, IO improvements
get-salt-AI/SaltAI pull request #3
Opened 2024-03-08 21:31 UTC by WAS-PlaiLabs

Introducing Salt AI's Llama-Index nodes, as well as some helper tools that could be useful with them. JPEG has been added to IO output, however ComfyUI doesn't appear to preview jpeg images.

2024-03-11 18:27 UTC, Tylermarques requested changes

2024-03-11 18:27 UTC, Tylermarques commented on nodes/io/input_output.py
> +                output_type = "JPEG" if output_type == "JPEG" else "PNG"
Is JPEG the default we want? I see your message to Katie in Slack, but we should review whether this change will break artcraft's return process.

2024-03-11 18:27 UTC, Tylermarques commented on nodes/SaltAI-Llama-Index/requirements.txt
Why both this `requirements.txt` and the one at the top level?

2024-03-11 18:27 UTC, Tylermarques commented on pyproject.toml
> +llama-index = "0.10.14"
Many of these are pinned at specific versions, can we relax that at all? maybe to minor versions instead? e.g. `llama-index = "^0.10"

2024-03-11 19:00 UTC, katieannbaker commented on nodes/io/input_output.py
> +                output_type = "JPEG" if output_type == "JPEG" else "PNG"
Functionally, this should work with Artcraft -  as long as the output structure is still the same and we can still pick up the bytes via the preview, we're not doing any additional validation in that layer about mimetype before pushing to the storage bucket

And I think PNG, unless the output type is explicitly set to JPEG, is likely the preferred behavior, too 👍 LGTM

2024-03-12 02:38 UTC, WAS-PlaiLabs commented on pyproject.toml
> +llama-index = "0.10.14"
There is tons of deprecation going on totally screwing functionality. Which is why it's all pinned to what works. Going any higher and he starts leaning on new `Settings` class which we haven't implemented at all, which involves all nodes.

2024-03-12 02:39 UTC, WAS-PlaiLabs commented on nodes/io/input_output.py
> +                output_type = "JPEG" if output_type == "JPEG" else "PNG"
Yeah it should be defaulting to PNG unless it's specifically set to JPEG. In this instance it's basically just this or that since it's the only two image output types.

2024-03-12 02:40 UTC, WAS-PlaiLabs commented on nodes/SaltAI-Llama-Index/requirements.txt
These can be checked out alone, as their own custom-nodes if for some reason people don't want SaltAI, such as no plan on using our platform and just want keyframing nodes or llama nodes. It was an idea I had since a lot of people complain of AIO node packs and wish they were more focused to what the person is downloading it for.

2024-03-12 13:25 UTC, Tylermarques approved these changes

2024-03-12 13:43 UTC, merged